### ISSUE TITLE
Specifying version doesn't work

### ISSUE THREAD

**Issue by Lastin** [rome/setup-rome#19]
Release 0.4 relates to commit 7554ef37c5cd86b378f5c8e48c78cab654d4815d
The fix has been implemented 4 commits later in c3eafc7fa5caab84463ceb06c7ef383c76e1ab4f but a release never created.

I've forked your repo and created release 0.5 and can confirm the fix works https://github.com/Lastin/setup-rome/releases/tag/v0.5

**Comment by elijaholmos** [comment]
You can point to the main branch with:

```yml
- name: Install Rome
        uses: rome/setup-rome@main
```

but yes, it would be preferable if @ematipico could publish a new release to include the latest changes

**Comment by ematipico** [comment]
Apologies! I am going to release a new version ASAP

**Comment by ematipico** [comment]
Released
